version: "3.9"

services:
  fastapi-server:
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - redis
      # - celery-worker
    environment:
      - MONGO_URI=${MONGO_URI}
      - IDEOGRAM_API_KEY=${IDEOGRAM_API_KEY}
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    env_file:
      - .env
    ports:
      - 8000:80
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  # celery-worker:
  #   build:
  #     context: backend
  #     dockerfile: Dockerfile
  #   command:
  #     [celery, -A, backend.celery_config, worker, --loglevel=info, --pool=solo]
  #   restart: always
  #   depends_on:
  #     - redis
  #   environment:
  #     - MONGO_URI=${MONGO_URI}
  #     - IDEOGRAM_API_KEY=${IDEOGRAM_API_KEY}
  #     - PYTHONPATH=/app
  #     - CELERY_BROKER_URL=redis://redis:6379
  #     - CELERY_RESULT_BACKEND=redis://redis:6379
  #   env_file:
  #     - backend/.env
